In [1]:
# Transpose A Matrix

In [2]:
import numpy as np

In [3]:
# Function Point

In [4]:
def transpose(a):
    new_arr = np.empty(a.shape)
    for i in range(a.shape[0]): # Row
        for j in range(a.shape[1]): # Column
            new_arr[j][i] = a[i][j]
    print(f"Transposed Array:\n{new_arr}")

In [5]:
# Execution Point

In [7]:
arr = np.array([
    [11, 55, 99],
[22, 44, 88],
[33, 77, 66]
])
print(f"Original array:\n{arr}\n")

transpose(arr)


Original array:
[[11 55 99]
 [22 44 88]
 [33 77 66]]

Transposed Array:
[[11. 22. 33.]
 [55. 44. 77.]
 [99. 88. 66.]]
