In [1]:
# Add two 2D matrices

In [2]:
import numpy as np

In [3]:
# Function Point

In [4]:
def addMatrices(a, b):
    for i in range(a.shape[0]): # Row
        for j in range(a.shape[1]): # Column
            a[i][j] = a[i][j] + b[i][j]
    print(f"Sum Matrix:\n{a}")

In [5]:
# Execution Point

In [6]:
arr1 = np.array([
    [1, 5, 9],
[2, 4, 8],
[3, 7, 6]
])
arr2 = np.array([
    [11, 55, 99],
[22, 44, 88],
[33, 77, 66]
])

print(f"Matrix 1:\n{arr1}\n\nMatrix 2:\n{arr2}\n\n")

addMatrices(arr1, arr2)


Matrix 1:
[[1 5 9]
 [2 4 8]
 [3 7 6]]

Matrix 2:
[[11 55 99]
 [22 44 88]
 [33 77 66]]


Sum Matrix:
[[ 12  60 108]
 [ 24  48  96]
 [ 36  84  72]]
